configTemplateName: common-config-temp
configTemplateId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/configTemplates/common-config-temp
versions:
  - version: 1.0.5
    configTemplateVersionId: /subscriptions/d1e52cbc-b073-42e2-a0a0-c2f547118a6e/resourceGroups/jn-ghawf-euap/providers/Microsoft.Edge/configTemplates/common-config-temp/versions/1.0.5
    revisions: []
  - version: 1.0.7
    configTemplateVersionId: ""
    revisions: []
